### ISSUE TITLE
Need to consolidate ingress rules into one file, otherwise api path does not work

### ISSUE THREAD

**Issue by nickveldrin** [seriohub/velero-helm#17]
Hello, i am trying to see if i can get this project to work, and while i'm still not exactly there, i had noticed that the helm chart deploys ingresses for both the UI as well as API.  When i try to hit the /api, it does not work, and the logon page of the UI is not able to reach it.

However, if i append the api pieces of the backend service to the UI ingress, the api is then reachable.

Sorry, i'm not sure how to fix the comment to show the code properly.
```
spec:
  ingressClassName: nginx
  rules:
  - host: velero.domain
    http:
      paths:
      - backend:
          service:
            name: velero-ui-vui-ui
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: velero-ui-vui-api
            port:
              number: 80
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: velero-ui-vui-api
            port:
              number: 80
        path: /ws
        pathType: Prefix
  tls:
  - hosts:
    - velero.domain
```
