### ISSUE TITLE
Can't Login velero-UI / Unreachable Cluster and API

### ISSUE THREAD

**Issue by ithesadson** [seriohub/velero-helm#29]
I installed velero ui with helm chart (with nodeport). Then when I accessed the interface, problems appeared on the login screen.
Velero works with a minio s3 installed locally. Does helm chart support it? 

Installation information is given below. Feel free to write for additional information.

values-override.yaml:
```
global:
  veleroNamespace: velero
  kubernetesClusterDomain: cluster.local

apiConfig:
  #Minio s3
  awsAccessKeyId: "xxx"
  awsSecretAccessKey: "xxx"
  veleroCliVersion: v1.7.0
  defaultAdminUsername: admin
  defaultAdminPassword: admin

uiNp:
  enabled: true
  apiPort: "30001"
  uiPort: "30002"

uiIngress:
  enabled: false
```
UI with nodePort:
![Screenshot from 2024-06-24 14-57-55](https://github.com/seriohub/velero-helm/assets/56589824/90fe14d4-39d3-4e4f-ae40-16da93da3e9e)

UI Pods:
![image](https://github.com/seriohub/velero-helm/assets/56589824/a4ab2847-cb08-4ed9-abba-0d30a4951bcb)

Velero pod: ( I backed up with velero and then restored from the backup. So the valero pod is working and there is no problem on this side.)
![image](https://github.com/seriohub/velero-helm/assets/56589824/7f26be75-c6be-40fd-9e57-f3ae4cf99e4d)
