### ISSUE TITLE
backup setup

### ISSUE THREAD

**Issue by clement-igonet** [seriohub/velero-helm#31]
From the UI, it would be very usefull to retrieve velero helm values or Schedule manifest for scheduling, in order to keep the link between web UI and velero low level setup.

Example:
* Schedule manifest
```yaml
apiVersion: velero.io/v1
kind: Schedule
(...)
spec:
  schedule: '@daily'
  skipImmediately: false
  template:
    csiSnapshotTimeout: 1h0m0s
    defaultVolumesToRestic: false
    excludedNamespaces:
    - kube-public
    - kube-system
    - velero
    hooks: {}
    includeClusterResources: true
    includedNamespaces:
    - '*'
    includedResources:
    - '*'
    itemOperationTimeout: 0s
    metadata: {}
    snapshotMoveData: true
    snapshotVolumes: true
    storageLocation: default
    ttl: 336h0m0s

```

* helm values:
```yaml
(...)
schedules:
  daily-backup:
    schedule: '@daily'
    template:
      csiSnapshotTimeout: 60m
      defaultVolumesToRestic: false
      excludedNamespaces:
      - kube-public
      - kube-system
      - velero
      includeClusterResources: true
      includedNamespaces:
      - '*'
      includedResources:
      - '*'
      snapshotMoveData: true
      snapshotVolumes: true
      storageLocation: default
      ttl: 336h
```
