### ISSUE TITLE
Error Client Side in browser (Chart 0.1.25)

### ISSUE THREAD

**Issue by L3st86** [seriohub/velero-helm#57]
I have been using your Chart since almost the beginning. I find it wonderful!
I went to upgrade from version 0.1.20 > 0.1.25  (also in 0.1.23 ) and I found the error that there was a problem on the client side and I looked in the console:

 TypeError: Cannot read properties of null (reading 'warning')
    at e7 (layout-3b30340af01b846e.js:1:14016)
    at rE (fd9d1056-7500e87e03f8f1a5.js:1:40344)
    at l$ (fd9d1056-7500e87e87e03f8f1a5.js:1:59319)
    at iZ (fd9d1056-7500e87e87e03f8f1a5.js:1:117926)
    at ia (fd9d1056-7500e87e87e03f8f1a5.js:1:95165)
    at fd9d1056-7500e87e03f8f1a5.js:1:94987
    at il (fd9d1056-7500e87e87e03f8f1a5.js:1:94994)
    at oJ (fd9d1056-7500e87e87e03f8f1a5.js:1:92350)
    at oZ (fd9d1056-7500e87e87e03f8f1a5.js:1:91769)
    at MessagePort.T (2117-cfdbdcbb64dbb5f6.js:1:84273)

I have updated the versions correctly as indicated in components:
| version | appVersion | api | ui | watchdog |
|------------|---------------|--------|--------|-----------|
| 0.1.25 | 0.2.2 | 0.2.2 | 0.2.2 | 0.1.7 |

Version 0.1.20 is stable for me:
| 0.1.20 | 0.1.18 | 0.1.21 | 0.1.20 | 0.1.6 |

Thanks

**Comment by L3st86** [comment]
Thank you for your prompt response.
Tried the 01.22 and its Ok. The problem started with | 0.1.23.
As soon as I try to log in, I get the following error in /dashboard.
Also tried other paths with no luck

![Image](https://github.com/user-attachments/assets/4a553a80-1ed7-48cd-93da-74b94f9bbe06)

I have tried incognito mode and clear cache.

Check page its Ok

![Image](https://github.com/user-attachments/assets/1ee2c440-1640-4a04-92d4-09fac2045a2b)


I only found the following error in watchdog logs:
2025-03-16 19:54:18,596 - dispatcher_apprise.py[101]->run - INFO APPRISE dispatcher: new element received
2025-03-16 19:54:18,596 - dispatcher_apprise.py[59]->send_msgs - ERROR No APPRISE config found
Theres is some new configurations that i am missing?

**Comment by davideserio** [comment]
The configurations for AppRise can be done directly from the UI or using the legacy keys for notifications via email, Slack, or Telegram.

If you'd like, you can share the values.yaml (or values-override.yaml) file you’re using so we can try to replicate the installation. Please make sure to mask any sensitive information

**Comment by L3st86** [comment]
Dear Friends,
Also tested updating velero client to last version v1.15.2, but not luck
Here  its my helmrelease:

```
    global:
      veleroNamespace: velero
      kubernetesClusterDomain: cluster.local
      agentMode: false
    #
    # API
    #
    api:
      apiServer:
        image:
          tag: 0.2.2
        imagePullPolicy: IfNotPresent
      ports:
      - name: velero-api
        port: 80
        protocol: TCP
        targetPort: api
      replicas: 1
      type: ClusterIP
    apiConfig:
      # -- Allowed origin
      origins1: 'https://velero-ui.local.domain.com'
      veleroCliVersion: v1.15.2
      defaultAdminUsername: admin
      defaultAdminPassword: admin

      storage:
        enabled: true
        storageClassName: "longhorn"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
    #
    # UI
    #
    ui:
      webServer:
        image:
          tag: 0.2.2

    #
    # UI Nodeport
    #
    uiNp:
      # -- Enable or disable nodeport
      enabled: false
 
    # Ingress
    #
    uiIngress:
      enabled: true
      ingressClassName: nginx
      # metadata:
      #   annotations:
      #     cert-manager.io/cluster-issuer: "letsencrypt-prod" 
      spec:
        tls:
          - hosts:
            - velero-ui.domain.com
            secretName: certificate
    #
    # Report
    #
    report:
      veleroWatchdogReport:
        image:
          tag: 0.1.7

    #
    # Watchdog Daemon
    #
    watchdog:
      veleroMonitoring:
        image:
          tag: 0.1.7
```
