### ISSUE TITLE
helm add annotation and tls ingresses

### ISSUE THREAD

**Issue by rchekhina** [seriohub/velero-helm#6]
HI,

On the helm chart can you add annotation and tls configuration please ?

to add the cert-manager cluster-issuer: 
```
metadata:
 annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
```

and the tls :
```
spec:
  tls:
  - hosts:
    - velero-ui.domain.com
    secretName: velero-ui-tls
```
Thanks in advance.

**Comment by rchekhina** [comment]
HI David,

thanks for this put you have removed the api ingress from the Chart.yml and the values.yml, is it normal ? I think that you need to do the same thing of ui for api.

Best regards.

**Comment by davideserio** [comment]
Hi,

We have implemented some changes to simplify the configuration. The API has been relocated to a new URL path  [prefix](https://github.com/seriohub/velero-helm/blob/9bea85ee58dbb1f4c839cb52c09064fef80dcb3d/seriohub-velero/templates/50_ingress.yaml#L19),  so only a single ingress is needed.

For clarity:
- UI URL: http(s)://your-domain.com
- API URL: http(s)://your-domain.com/api

I suggest utilizing the latest version of the Helm chart available (now [v0.1.5](https://github.com/seriohub/velero-helm/blob/9bea85ee58dbb1f4c839cb52c09064fef80dcb3d/seriohub-velero/Chart.yaml)) and the new [values override file](https://github.com/seriohub/velero-helm/blob/main/values-override.yaml).

Please let us know if you encounter any problems.

**Comment by rchekhina** [comment]
HI David,
ok thanks for the information.
I have tried the tls configuration like following but it did not work. The annotation and the tls conf didnt appear on the ingress:

```
uiIngress:
  enabled: true
  # ingressClassName: nginx
  host: velero.domain.com
  tls:
    enabled: true
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod" 
    spec:
      tls:
       - hosts:
         - velero.domain.com
         secretName: velero-ui-tls
```

can you help me please ?

**Comment by davideserio** [comment]
We have released a new version with various corrections. 
Please let us know if you encounter any problems or if the installation is successful.

**Comment by rchekhina** [comment]
HI Davide,

I confirm that now the annotation and tls config works like following:

```
uiIngress:
  enabled: true
  # ingressClassName: nginx
  host: velero.domain.com
  tls:
    enabled: true
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod" 
  spec:
    tls:
     - hosts:
       - velero.domain.com
       secretName: velero-ui-tls
```
Best regards.
