### ISSUE TITLE
Watchdog deployment label selector

### ISSUE THREAD

**Issue by brightdroid** [seriohub/velero-helm#66]
I think the selector is wrong:
```yaml
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero-ui
      app.kubernetes.io/name: vui
      tier: backend
```
This selects also "velero-ui-vui-api" pods.
