### ISSUE TITLE
Will you add velero-helm to https://artifacthub.io/ 

### ISSUE THREAD

**Issue by rchekhina** [seriohub/velero-helm#7]
HI,

Will you add velero-helm to https://artifacthub.io/  ?
Its to deploy it with argocd.

Best regards.

**Comment by davideserio** [comment]
I have updated the README with instructions for using a repository. You can find the details in the [README](https://github.com/seriohub/velero-helm/blob/main/README.md) file.
Please let us know if you encounter any problems or if the installation is successful.

**Comment by rchekhina** [comment]
HI Davide,

ok thanks for this. I have successfully deploy it with kustomize like following:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
generatorOptions:
  disableNameSuffixHash: true

helmCharts:
- name: vui
  repo: https://seriohub.github.io/velero-helm/
  version: 0.1.6
  releaseName: velero-ui
  valuesFile: ./values.yaml
  namespace: velero-ui
resources:
  - velero-ui-ns.yaml
```

Best regards.
